[package]
name = "messaging"
edition.workspace = true
version.workspace = true


[dependencies]
anyhow = "*"
async-trait = "*"
bytes = "*"
rustc-hash = "*"
tokio = { version = "*", features = ["full"] } # TODO
tracing = "*"